# Generated by Django 4.2 on 2023-04-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_countrycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='countrycode',
            field=models.CharField(max_length=2, null=True, verbose_name='Countrycode +   '),
        ),
    ]
