# Generated by Django 4.2 on 2023-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='countrycode',
            field=models.CharField(max_length=2, null=True, verbose_name='Countrycode /"+"/'),
        ),
    ]
