# Generated by Django 4.2 on 2023-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_transaction_status_order_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
